name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aext-assistant=4.1.0=py312haa95532_jl4_0
  - aext-assistant-server=4.1.0=py312haa95532_0
  - aext-core=4.1.0=py312haa95532_jl4_0
  - aext-core-server=4.1.0=py312haa95532_0
  - aext-panels=4.1.0=py312haa95532_0
  - aext-panels-server=4.1.0=py312haa95532_0
  - aext-project-filebrowser-server=4.1.0=py312haa95532_0
  - aext-share-notebook=4.1.0=py312haa95532_0
  - aext-share-notebook-server=4.1.0=py312haa95532_0
  - aext-shared=4.1.0=py312haa95532_0
  - alembic=1.13.3=py312haa95532_0
  - anaconda-anon-usage=0.7.5=pyhb46e38b_100
  - anaconda-auth=0.12.3=py312haa95532_0
  - anaconda-catalogs=0.2.0=py312haa95532_1
  - anaconda-cli-base=0.7.0=py312haa95532_0
  - anaconda-client=1.13.0=py312haa95532_0
  - anaconda-cloud-auth=0.12.3=py312haa95532_0
  - anaconda-navigator=2.7.0=py312haa95532_1
  - anaconda-project=0.11.1=py312haa95532_0
  - anaconda-toolbox=4.1.0=py312haa95532_0
  - anaconda_powershell_prompt=1.1.0=haa95532_0
  - anaconda_prompt=1.1.0=haa95532_0
  - annotated-types=0.6.0=py312haa95532_0
  - anyio=4.2.0=py312haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312haa95532_0
  - attrs=23.1.0=py312haa95532_0
  - babel=2.11.0=py312haa95532_0
  - bcrypt=4.3.0=py312h636fa0f_0
  - beautifulsoup4=4.12.3=py312haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=3.6.0=py312haa95532_0
  - boltons=23.0.0=py312haa95532_0
  - bottleneck=1.3.7=py312he558020_0
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py312haa95532_0
  - cffi=1.17.1=py312h827c3e9_0
  - chardet=4.0.0=py312haa95532_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - conda=24.11.3=py312haa95532_0
  - conda-build=24.9.0=py312haa95532_0
  - conda-content-trust=0.2.0=py312haa95532_1
  - conda-index=0.5.0=py312haa95532_0
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-pack=0.7.1=py312haa95532_0
  - conda-package-handling=2.3.0=py312haa95532_0
  - conda-package-streaming=0.10.0=py312haa95532_0
  - conda-repo-cli=1.0.114=py312haa95532_0
  - conda-token=0.7.0=hd3eb1b0_0
  - cryptography=43.0.0=py312h89fc84f_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - filelock=3.13.1=py312haa95532_0
  - fmt=9.1.0=h6d14046_1
  - fontconfig=2.14.1=hb33846d_3
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozendict=2.4.2=py312haa95532_0
  - frozenlist=1.4.0=py312h2bbff1b_0
  - fsspec=2024.6.1=py312haa95532_0
  - graphite2=1.3.14=hd77b12b_1
  - greenlet=3.0.1=py312hd77b12b_0
  - h11=0.14.0=py312haa95532_0
  - harfbuzz=10.2.0=he2f9f60_1
  - httpcore=1.0.2=py312haa95532_0
  - httpx=0.27.0=py312haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - intake=2.0.7=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py312haa95532_1
  - ipython=8.27.0=py312haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py312haa95532_0
  - jinja2=3.1.4=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.33=py312haa95532_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter-lsp=2.2.0=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyter_events=0.10.0=py312haa95532_0
  - jupyter_server=2.14.1=py312haa95532_0
  - jupyter_server_terminals=0.4.4=py312haa95532_1
  - jupyterlab=4.2.5=py312haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - keyring=24.3.1=py312haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-object-proxy=1.10.0=py312h2bbff1b_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libarchive=3.7.7=h9243413_0
  - libavif=1.3.0=h5bd13ec_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang=20.1.8=default_h643f374_0
  - libclang13=20.1.8=default_hccbf073_0
  - libcurl=8.17.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=13_h018ca30_netlib
  - liblief=0.12.3=hd77b12b_0
  - libllvm20=20.1.8=h3aa9ab2_0
  - libmamba=1.5.8=h99b1521_3
  - libmambapy=1.5.8=py312h77c03ed_3
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.18=h62dcd97_0
  - libsolv=0.7.24=h23ce68f_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.0=py312haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.2.3=py312haa95532_0
  - markdown=3.4.1=py312haa95532_0
  - markdown-it-py=2.2.0=py312haa95532_1
  - markupsafe=2.1.3=py312h2bbff1b_0
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mdit-py-plugins=0.3.0=py312haa95532_0
  - mdurl=0.1.0=py312haa95532_0
  - menuinst=2.1.2=py312h5da7b33_0
  - mistune=2.0.4=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.10=py312h827c3e9_0
  - mkl_random=1.2.7=py312h0158946_0
  - more-itertools=10.3.0=py312haa95532_0
  - mpmath=1.3.0=py312haa95532_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py312h2bbff1b_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - navigator-updater=0.6.0=py312haa95532_0
  - nb_conda_kernels=2.5.2=py312haa95532_0
  - nbclient=0.8.0=py312haa95532_0
  - nbconvert=7.16.4=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.3=py312haa95532_0
  - notebook=7.2.2=py312haa95532_1
  - notebook-shim=0.2.3=py312haa95532_0
  - numexpr=2.8.7=py312h96b7d27_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.4.0=py312haa95532_0
  - packaging=24.1=py312haa95532_0
  - pandas=2.2.2=py312h0158946_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.5.2=py312haa95532_0
  - param=2.1.1=py312haa95532_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=h0ff8eda_0
  - pillow=12.0.0=py312h4212202_1
  - pip=24.2=py312haa95532_0
  - pixman=0.46.4=h4043f72_0
  - pkce=1.0.3=py312haa95532_0
  - pkginfo=1.10.0=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - pluggy=1.0.0=py312haa95532_1
  - ply=3.11=py312haa95532_1
  - prometheus_client=0.14.1=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.4.1=py312h02ab6af_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py312hd77b12b_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h2bbff1b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py312haa95532_0
  - pydantic-core=2.20.1=py312hefb1915_0
  - pydantic-settings=2.6.1=py312haa95532_0
  - pygments=2.15.1=py312haa95532_1
  - pyjwt=2.8.0=py312haa95532_0
  - pynacl=1.5.0=py312h8cc25b3_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pyqtwebengine=5.15.10=py312hd77b12b_0
  - pyside6=6.9.2=py312h151a370_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.8=h14ffc60_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-dotenv=0.21.0=py312haa95532_0
  - python-fastjsonschema=2.16.2=py312haa95532_0
  - python-json-logger=2.0.7=py312haa95532_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2024.1=py312haa95532_0
  - pyviz_comms=3.0.2=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pywin32-ctypes=0.2.2=py312haa95532_0
  - pywinpty=2.0.10=py312h5da7b33_0
  - pyyaml=6.0.1=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - qt-main=5.15.2=h8b2cd8b_13
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtpy=2.4.1=py312haa95532_0
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hebbe641_0
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - readchar=4.0.5=py312haa95532_0
  - referencing=0.30.2=py312haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.3=py312haa95532_0
  - requests-toolbelt=1.0.0=py312haa95532_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rich=13.7.1=py312haa95532_0
  - rpds-py=0.10.6=py312h062c2fa_0
  - ruamel.yaml=0.18.6=py312h827c3e9_0
  - ruamel.yaml.clib=0.2.8=py312h827c3e9_0
  - ruamel_yaml=0.17.21=py312h2bbff1b_0
  - semver=3.0.2=py312haa95532_0
  - send2trash=1.8.2=py312haa95532_0
  - sentry-sdk=2.18.0=py312haa95532_0
  - setuptools=75.1.0=py312haa95532_0
  - shellingham=1.5.0=py312haa95532_0
  - sip=6.7.12=py312hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py312haa95532_0
  - soupsieve=2.5=py312haa95532_0
  - sqlalchemy=2.0.34=py312h54f65d0_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py312haa95532_0
  - tinycss2=1.2.1=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.0.1=py312haa95532_1
  - tornado=6.4.1=py312h827c3e9_0
  - tqdm=4.66.5=py312hfc267ef_0
  - traitlets=5.14.3=py312haa95532_0
  - truststore=0.8.0=py312haa95532_0
  - typer=0.20.0=py312haa95532_0
  - typer-slim=0.20.0=py312haa95532_0
  - typer-slim-standard=0.20.0=py312haa95532_0
  - typing-extensions=4.11.0=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2024b=h04d1e81_0
  - uc-micro-py=1.0.1=py312haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.10.0=py312h5da7b33_0
  - urllib3=2.2.3=py312haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=4.0.1=py312haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xyzservices=2022.9.0=py312haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_1
  - yarl=1.22.0=py312h02ab6af_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.24.0=py312he335c29_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - ale-py==0.11.2
      - contourpy==1.3.3
      - farama-notifications==0.0.4
      - grpcio==1.76.0
      - gymnasium==1.2.3
      - mouseinfo==0.1.3
      - mplfinance==0.12.10b0
      - mss==10.1.0
      - nodejs-wheel-binaries==24.13.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pyautogui==0.9.54
      - pygame==2.6.1
      - pygetwindow==0.0.9
      - pymsgbox==2.0.1
      - pyperclip==1.11.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytesseract==0.3.13
      - pytubefix==10.3.6
      - pytweening==1.2.0
      - stable-baselines3==2.7.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.9.1
prefix: C:\Users\USER\.anaconda
